name: Build and Publish 📦 to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  build-n-publish:
    name: Build and Publish 💫
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install React Dependencies
        run: npm ci

      - name: Build the Package
        run: npm run build

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
